# Generated by Django 2.0.3 on 2018-05-04 21:31

from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_time', models.DateTimeField()),
                ('praise_numbers1', models.IntegerField()),
                ('critical_numbers', models.IntegerField()),
                ('answer_content', tinymce.models.HTMLField()),
            ],
        ),
        migrations.CreateModel(
            name='Attention',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='PracticeInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('practice_name', models.CharField(max_length=100)),
                ('practice', tinymce.models.HTMLField()),
                ('course_belong', models.CharField(max_length=100)),
                ('up_time', models.DateTimeField()),
                ('adjust_class', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_title', models.CharField(max_length=100)),
                ('questions_content', tinymce.models.HTMLField()),
                ('attentions_number', models.IntegerField()),
                ('anonymity', models.CharField(max_length=10)),
                ('author_name', models.CharField(max_length=20)),
                ('sub_time', models.DateTimeField()),
                ('answers_number', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='StudentInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s_number', models.IntegerField()),
                ('s_name', models.CharField(max_length=20)),
                ('s_pwd', models.IntegerField()),
                ('s_class', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='StudentPractice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('practice_author', models.CharField(max_length=30)),
                ('sub_time', models.DateTimeField()),
                ('author_class', models.CharField(max_length=30)),
                ('s_result', models.CharField(max_length=20)),
                ('teacher_id', models.CharField(max_length=20)),
                ('practice_content', tinymce.models.HTMLField()),
                ('practice_name', models.CharField(max_length=20)),
                ('practice_authornumber', models.CharField(max_length=20)),
                ('practice_results', models.CharField(max_length=1000)),
                ('subauthor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='imysql.StudentInfo')),
            ],
        ),
        migrations.CreateModel(
            name='TeacherInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('t_number', models.IntegerField()),
                ('t_name', models.CharField(max_length=20)),
                ('t_pwd', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='question',
            name='student_author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='imysql.StudentInfo'),
        ),
        migrations.AddField(
            model_name='question',
            name='teacher_author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='imysql.TeacherInfo'),
        ),
        migrations.AddField(
            model_name='practiceinfo',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='imysql.TeacherInfo'),
        ),
        migrations.AddField(
            model_name='attention',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='imysql.Question'),
        ),
        migrations.AddField(
            model_name='attention',
            name='student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='imysql.StudentInfo'),
        ),
        migrations.AddField(
            model_name='attention',
            name='teacher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='imysql.TeacherInfo'),
        ),
        migrations.AddField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='imysql.Question'),
        ),
        migrations.AddField(
            model_name='answer',
            name='s_answer_num',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='imysql.TeacherInfo'),
        ),
        migrations.AddField(
            model_name='answer',
            name='t_answer_num',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='imysql.StudentInfo'),
        ),
    ]
