# Generated by Django 2.0.3 on 2018-05-05 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imysql', '0002_auto_20180505_1522'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='answer_name',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
