# Generated by Django 2.0.3 on 2018-05-09 15:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('imysql', '0003_answer_answer_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestFiles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('testname', models.CharField(max_length=20)),
                ('sub_time', models.DateTimeField()),
                ('adjust_class', models.CharField(max_length=20)),
                ('saveaddress', models.CharField(max_length=100)),
                ('author_num', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='imysql.TeacherInfo')),
            ],
        ),
    ]
