# Generated by Django 2.0.3 on 2018-05-10 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imysql', '0004_testfiles'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enterinfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=20)),
                ('enter_time', models.DateTimeField()),
                ('s_class', models.CharField(max_length=20)),
            ],
        ),
    ]
