# Generated by Django 2.0.3 on 2018-05-12 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imysql', '0005_enterinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentinfo',
            name='company',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='studentinfo',
            name='e_mail',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='studentinfo',
            name='major',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='studentinfo',
            name='phone_number',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='studentinfo',
            name='photo_address',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='studentinfo',
            name='position',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='studentinfo',
            name='school',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='studentinfo',
            name='sex',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='studentinfo',
            name='sign',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='studentinfo',
            name='work',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='teacherinfo',
            name='company',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='teacherinfo',
            name='e_mail',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='teacherinfo',
            name='major',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='teacherinfo',
            name='phone_number',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='teacherinfo',
            name='photo_address',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='teacherinfo',
            name='position',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='teacherinfo',
            name='school',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='teacherinfo',
            name='sex',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='teacherinfo',
            name='sign',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='teacherinfo',
            name='work',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
