# Generated by Django 2.0.3 on 2018-05-14 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imysql', '0006_auto_20180512_1641'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentinfo',
            name='phone_number',
            field=models.CharField(max_length=110, null=True),
        ),
        migrations.AlterField(
            model_name='teacherinfo',
            name='phone_number',
            field=models.CharField(max_length=110, null=True),
        ),
    ]
