# Generated by Django 2.0.3 on 2018-05-18 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imysql', '0007_auto_20180514_0021'),
    ]

    operations = [
        migrations.AddField(
            model_name='practiceinfo',
            name='answer',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
