
from django.conf.urls import url
from . import views
urlpatterns = [
    url(r'^enter$',views.enter),
    url(r'^handle$',views.handle),
    url(r'^shomepage/(.*)$',views.shomepage),
    url(r'^thomepage/(.*)$', views.thomepage),
    url(r'^t_practice$',views.t_practice),
    url(r'^add_practice',views.add_practice),
    url(r'^add_handle$',views.add_handle),
    url(r'^t_practice2/$',views.t_practice2),
    url(r'^d_practice/(\d+)/$',views.d_practice),
    url(r'^get_practice$',views.get_practice),
    url(r'^get_handle/(.+)/$',views.get_handle),
    #url(r'^sub_practice/(.+)$',views.sub_practice),
    url(r'^sub_handle/(.+)/(.+)/(.+)/$',views.sub_handle),
    url(r'^see_result/$',views.see_result),
    url(r'^see_resulthandle/$',views.see_resulthandle),
    url(r'^results/(\d+)/',views.results),
    url(r'^t_results/(\d+)/', views.t_results),
    url(r'^sd_practice/(\d+)/$', views.sd_practice),
    url(r'^td_practice/(\d+)/$', views.td_practice),
    url(r'^query_result/$',views.query_result),
    url(r'^query_resulthandle$',views.query_resulthandle),
    url(r'^query_resulthandle2/(.+)/$', views.query_resulthandle2),
    url(r'^query2$',views.query2),
    url(r'^s_question$',views.s_question),
    url(r'^t_question$',views.t_question),
    url(r'^s_questionhandle$',views.s_questionhandle),
    url(r'^t_questionhandle$',views.t_questionhandle),
    url(r'^get_question/(.*)$',views.get_question),
    url(r'^sget_newquestion/(.*)$',views.sget_newquestion),
    url(r'^get_newquestionhandle/(.*)$',views.get_newquestionhandle),
    url(r'^tget_newquestion/(.*)$',views.tget_newquestion),
    url(r'^attention/(\d+)/$',views.attention),
    url(r'^squestiondetail/(\d+)/$',views.squestiondetail),
    url(r'^sanswerhandle/(\d+)/$',views.sanswerhandle),
    url(r'^getanswers/(\d+)/$',views.getanswers),
    url(r'^sdislike/(\d+)/(\d+)/$',views.sdislike),
    url(r'^sattention2/(\d+)/(\d+)/$',views.sattention2),
    url(r'^tquestiondetail/(\d+)/$', views.tquestiondetail),
    url(r'^tanswerhandle/(\d+)/$', views.tanswerhandle),
    url(r'^tdislike/(\d+)/(\d+)/$', views.tdislike),
    url(r'^tattention2/(\d+)/(\d+)/$', views.tattention2),
    url(r'^tget_attentions$',views.tget_attentions),
    url(r'^sget_attentions$',views.sget_attentions),
    url(r'^get_attentionshandle$',views.get_attentionshandle),
    url(r'^sget_myanswer$',views.sget_myanswer),
    url(r'^tget_myanswer$', views.tget_myanswer),
    url(r'^get_myanswerhandle$',views.get_myanswerhandle),
    url(r'^sget_myanswer$',views.sget_myquestion),
    url(r'^sget_myquestion$',views.sget_myquestion),
    url(r'^tget_myquestion',views.tget_myquestion),
    url(r'^get_myquestionhandle$',views.get_myquestionhandle),
    url(r'^uploadFiles$',views.uploadFiles),
    url(r'^uploadHandle$',views.uploadHandle),
    url(r'^see_testfileshandle$',views.see_testfileshandle),
    url(r'^see_testfiles$',views.see_testfiles),
    url(r'^download/(.+)/(.+)/$',views.download),
    url(r'^td_testfiles/(.+)/$',views.td_testfiles),
    url(r'^s_gettestfiles$',views.s_gettestfiles),
    url(r'^query_testfiles$',views.query_testfiles),
    url(r'^query_testfileshandle/(.+)/$',views.query_testfileshandle),
    url(r'^senter_info$',views.senter_info),
    url(r'^enter_infohandle$',views.enter_infohandle),
    url(r'^query_enterinfo$',views.query_enterinfo),
    url(r'^query_enterinfohandle/(.+)/$',views.query_enterinfohandle),
    url(r'^info$',views.info),
    url(r'^infohandle$',views.infohandle),
    url(r'^about$',views.about),
    url(r'^see_practice/(\d+)/$',views.see_practice),
    url(r'^sqlknowledge$',views.sqlknowledge),

]